
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SVIS
 */
public class Net_Banking extends javax.swing.JFrame {

    /**
     * Creates new form Net_Banking
     */
    public Net_Banking() {
        initComponents();
    }

     public Net_Banking(String name,int price) {
        initComponents();
        jLabel1.setVisible(true);
        int pri=price;
        String nam=name;
        jLabel1.setText(nam);
        jLabel4.setText(Integer.toString(pri));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabe1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Banks ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 270, 128, 19);

        jRadioButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/idbi_bank.png"))); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(38, 183, 180, 59);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Next>>");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 470, 90, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 300, 200, 37);

        jLabe1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabe1.setForeground(new java.awt.Color(255, 0, 0));
        jLabe1.setText("NET BANKING");
        jPanel1.add(jLabe1);
        jLabe1.setBounds(230, 10, 210, 33);

        jRadioButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/citi_bank.png"))); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(244, 81, 190, 60);

        jRadioButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/sbi-na.png"))); // NOI18N
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(458, 191, 192, 51);

        jRadioButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Kotak_Mahindra_Bank_logo.png"))); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(38, 79, 180, 60);

        jRadioButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/hdfc_bank.png"))); // NOI18N
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(239, 191, 201, 50);

        jRadioButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/icici_bank.png"))); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(460, 70, 200, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Amount to be paid:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(380, 370, 150, 29);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(540, 370, 107, 29);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(610, 320, 0, 0);

        Label17.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Label17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Label17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String n2=null;
         String u2=jLabel1.getText();
         int price=Integer.parseInt(jLabel4.getText());
         if(jRadioButton1.isSelected()==true)
         {
             n2="Kotak Bank";
         }
         else if(jRadioButton2.isSelected()==true)
         {
             n2="CitiBank";
         }
         else if(jRadioButton3.isSelected()==true)
         {
             n2="ICIC Bank";
         }
         else if(jRadioButton4.isSelected()==true)
         {
             n2="IDBI Bank";
         }
         else if(jRadioButton5.isSelected()==true)
         {
             n2="HDFC Bank";
         }
         else if(jRadioButton6.isSelected()==true)
         {
             n2="SBI Bank";
         }
         Net_Banking_2 bp= new Net_Banking_2(n2,u2,price);
        this.setVisible(false);
        bp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         Net_Banking_2 n2= new Net_Banking_2();
        if(jRadioButton2.isSelected()==true)
        jTextField1.setText("Citibank");
        jButton1.setEnabled(true);
        n2.jLabel1.setText("CitiBank");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
         Net_Banking_2 n2= new Net_Banking_2();
        if(jRadioButton6.isSelected()==true)
        jTextField1.setText("SBI Bank");
        jButton1.setEnabled(true);
        n2.jLabel1.setText("SBI Bank");
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
         Net_Banking_2 n2= new Net_Banking_2();
        if(jRadioButton1.isSelected()==true)
        jTextField1.setText("Kotak bank");
        jButton1.setEnabled(true);
        n2.jLabel1.setText("Kotak Bank");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        Net_Banking_2 n2= new Net_Banking_2();
        if(jRadioButton5.isSelected()==true)
        jTextField1.setText("HDFC Bank");
        jButton1.setEnabled(true);
        n2.jLabel1.setText("HDFC Bank");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
         Net_Banking_2 n2= new Net_Banking_2();
        if(jRadioButton3.isSelected()==true)
        jTextField1.setText("ICIC Bank");
        jButton1.setEnabled(true);
        n2.jLabel1.setText("ICIC Bank");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Net_Banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Net_Banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Net_Banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Net_Banking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Net_Banking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Label17;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabe1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
