import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sirish
 */
public class Seller_page_new_product extends javax.swing.JFrame {

    /**
     * Creates new form Seller_page_new_product
     */
    public Seller_page_new_product() {
        initComponents();
    }

   public Seller_page_new_product(String nam) {
         initComponents();
         String na=nam;
         jLabel6.setText(na);
         jLabel6.setVisible(false);
         jLabel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Product name");

        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Quantity");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Description");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Product_type");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Product Type:", "TV, Appliances, Electronics", "Clothing", "Home, Kitchen, Pets", "Beauty, Health, Grocery", "Sports, Fitness, Bags, Luggage", "Toys, Baby Products, Kids' Fashion", "Car, Motorbike, Industrial", "Books", "Movies, Music & Video Games", "Gift Cards", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Product_Category");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("<<Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("ADD NEW PRODUCTS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 272, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 266, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 266, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 266, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 266, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 313, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 313, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 313, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 313, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().length()==0 || jTextField1.getText().length()==0 
                || jTextField3.getText().length()==0 || jComboBox2.getSelectedIndex()==0 
                || jComboBox1.getSelectedIndex()==0 || jTextArea1.getText().length()==0 
                )
        {
              JOptionPane.showMessageDialog(this,"Please enter all data!");
        }          
        else
        {
            String pname=jTextField1.getText();
            int quantity=Integer.parseInt(jTextField2.getText());
            int price=Integer.parseInt(jTextField3.getText());
            String desc=jTextArea1.getText();
            String name=jLabel6.getText();
            String type=(String) jComboBox1.getSelectedItem();
            String cat=(String) jComboBox2.getSelectedItem();
            String u=jLabel5.getText();
            String p="P";
            try
            {  
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ip_project","root","admin");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/seller_accounts","root","admin");
            Statement s=con.createStatement();
            String f="select count(*) from product;";
            ResultSet r=s.executeQuery(f);
            r.last();
            int qq=r.getInt("count(*)");
            if(qq==0)
            { 
                String a ="1";
                String pid=p.concat(a);
                Statement st=con.createStatement();
                String q="insert into product values('"+pname+"','"+quantity+"','"+price+"','"+desc+"','"+type+"','"+cat+"','"+pid+"','"+name+"');";
                st.executeUpdate(q);
                Statement stm=co.createStatement();
                String k="insert into "+name+" values('"+pid+"','"+pname+"','"+quantity+"','"+price+"','"+desc+"','"+type+"','"+cat+"');";
                stm.executeUpdate(k);
                
            }
            else
            { 
                Statement stmt=con.createStatement();
                String ft="select P_ID from product;";
                ResultSet rt=stmt.executeQuery(ft);
                rt.last();
                String pi=rt.getString("P_ID");
                int y=Integer.parseInt(pi.substring(1));
                y++;
                String id=Integer.toString(y);
                String pid=p.concat(id);
                Statement st=con.createStatement();
                String q="insert into product values('"+pname+"','"+quantity+"','"+price+"','"+desc+"','"+type+"','"+cat+"','"+pid+"','"+name+"');";
                st.executeUpdate(q);
                Statement stm=co.createStatement();
                String k="insert into "+name+" values('"+pid+"','"+pname+"','"+quantity+"','"+price+"','"+desc+"','"+type+"','"+cat+"');";
                stm.executeUpdate(k);
                
            } 
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
        jTextField1.setText(" ");
        jTextField2.setText(" ");
        jTextField3.setText(" ");
        jTextArea1.setText(" ");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==1)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Televisions");
          jComboBox2.addItem("Smartphones, Mobile phones and accesories");
          jComboBox2.addItem("Home Entertainment Systems");
          jComboBox2.addItem("Headphones");
          jComboBox2.addItem("Speaker");
          jComboBox2.addItem("MP3, Media Players & Accessories");
          jComboBox2.addItem("Audio & Video Accessories");
          jComboBox2.addItem("Cameras");
          jComboBox2.addItem("DSLR Cameras");
          jComboBox2.addItem("Camera Accessories");
          jComboBox2.addItem("Musical Instruments & Professional Audio");
          jComboBox2.addItem("Gaming Consoles");
          jComboBox2.addItem("Air Conditioners"); 
          jComboBox2.addItem("Refrigerators"); 
          jComboBox2.addItem("Washing Machines"); 
          jComboBox2.addItem("Kitchen & Home Appliances"); 
          jComboBox2.addItem("Heating & Cooling Appliances"); 
        }
        else if(jComboBox1.getSelectedIndex()==2)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Mens Clothing");
          jComboBox2.addItem("Female Clothing");
        }
        else if(jComboBox1.getSelectedIndex()==3)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Kitchen & Dining");
          jComboBox2.addItem("Kitchen Storage & Containers");
          jComboBox2.addItem("Furniture");
          jComboBox2.addItem("Fine Art");
          jComboBox2.addItem("Home Furnishing");
          jComboBox2.addItem("Bedroom Linen");
          jComboBox2.addItem("Home Décor");
          jComboBox2.addItem("Home Storage");
          jComboBox2.addItem("Indoor Lighting"); 
          jComboBox2.addItem("Home Improvement");  
          jComboBox2.addItem("All Home & Kitchen"); 
          jComboBox2.addItem("Shop by Room"); 
          jComboBox2.addItem("Home & Kitchen Deals");  
          jComboBox2.addItem("Dog supplies"); 
        }
        else if(jComboBox1.getSelectedIndex()==4)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Beauty & Grooming");
          jComboBox2.addItem("Luxury Beauty");
          jComboBox2.addItem("Make-up");
          jComboBox2.addItem("Health & Personal Care");
          jComboBox2.addItem("Household Supplies");
          jComboBox2.addItem("Diet & Nutrition");
          jComboBox2.addItem("Subscribe & Save");
          jComboBox2.addItem("Value Bazaar");
          jComboBox2.addItem("All Grocery & Gourmet Foods");
          jComboBox2.addItem("Beauty Servies"); 
          jComboBox2.addItem("Home Improvement"); 
          jComboBox2.addItem("Snack Foods"); 
        }       
        else if(jComboBox1.getSelectedIndex()==5)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Cricket");
          jComboBox2.addItem("Badminton");
          jComboBox2.addItem("Cycling");
          jComboBox2.addItem("Football");
          jComboBox2.addItem("Running");
          jComboBox2.addItem("Camping & Hiking");
          jComboBox2.addItem("Yoga");
          jComboBox2.addItem("Strength Training");
          jComboBox2.addItem("Cardio Equipment"); 
          jComboBox2.addItem("All Exercise & Fitness");  
          jComboBox2.addItem("All Sports, Fitness & Outdoors"); 
          jComboBox2.addItem("Backpacks"); 
          jComboBox2.addItem("Rucksacks"); 
          jComboBox2.addItem("Suitcases & Trolley Bags"); 
          jComboBox2.addItem("Travel Duffles"); 
          jComboBox2.addItem("Travel Accessories"); 
          jComboBox2.addItem("Wallets"); 
        }
        else if(jComboBox1.getSelectedIndex()==6)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Toys & Games");
          jComboBox2.addItem("Baby Products");
          jComboBox2.addItem("Diapers");
          jComboBox2.addItem("Baby Wish List");
          jComboBox2.addItem("Toys Gifting Store");
          jComboBox2.addItem("STEM Toys Store");
          jComboBox2.addItem("International Toy Store");
          jComboBox2.addItem("Baby Bath, Skin & Grooming");
          jComboBox2.addItem("Strollers & Prams");  
          jComboBox2.addItem("Subscribe & Save"); 
          jComboBox2.addItem("Kids' Shoes"); 
          jComboBox2.addItem("School Bags"); 
          jComboBox2.addItem("Kids' Clothing"); 
          jComboBox2.addItem("Kids' Watches"); 
          jComboBox2.addItem("Kids' Fashion"); 
          jComboBox2.addItem("Baby Fashion"); 
        }
        else if(jComboBox1.getSelectedIndex()==7)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Motorbike Accessories & Parts");
          jComboBox2.addItem("Car Accessories");
          jComboBox2.addItem("Car Electronics");
          jComboBox2.addItem("Car Parts");
          jComboBox2.addItem("Car & Bike Care");
          jComboBox2.addItem("All Car & Motorbike Products");
          jComboBox2.addItem("Test, Measure & Inspect");
          jComboBox2.addItem("Lab & Scientific");
          jComboBox2.addItem("Janitorial & Sanitation Suppliest");  
        }
        else if(jComboBox1.getSelectedIndex()==8)
        {
          jComboBox2.removeAllItems();  
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Fiction Books");
          jComboBox2.addItem("Editor's Corner");
          jComboBox2.addItem("School Textbooks");
          jComboBox2.addItem("Children's Books");
          jComboBox2.addItem("Exam Central");
          jComboBox2.addItem("Textbooks");
          jComboBox2.addItem("Indian Language Books");
          jComboBox2.addItem("Used Books"); 
        }
        else if(jComboBox1.getSelectedIndex()==9)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Gaming Consoles");
          jComboBox2.addItem("Latest Video Games");
          jComboBox2.addItem("Gaming Accessories");
          jComboBox2.addItem("PC Games");
          jComboBox2.addItem("Video Games Deals");
          jComboBox2.addItem("Film Songs");
          jComboBox2.addItem("Indian Classical");
          jComboBox2.addItem("Musical Instruments & Professional Audio");
          jComboBox2.addItem("Blu-ray");
        }
        else if(jComboBox1.getSelectedIndex()==10)
        {
          jComboBox2.removeAllItems();
          jComboBox2.addItem("Select Product Category");
          jComboBox2.addItem("Birthday Gift Cards");
          jComboBox2.addItem("Gift Boxes, Gift Tags, Greeting Cards");
          jComboBox2.addItem("Wedding & Anniversary");
          jComboBox2.addItem("Best Wishes & Thank You");
          jComboBox2.addItem("Corporate Gift Cards");
        }   
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nam=jLabel6.getText();
        this .setVisible(false);
        new seller_page_1(nam).setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed
       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seller_page_new_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seller_page_new_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seller_page_new_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seller_page_new_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seller_page_new_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
